In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('weight-height.csv - weight-height.csv.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
df.Gender = le.fit_transform(df['Gender'])

In [8]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
mms = MinMaxScaler()

In [11]:
df['Weight'] = mms.fit_transform(df[['Weight']])

In [12]:
df['Height'] = mms.fit_transform(df[['Height']])

In [13]:
df.head()

Gender    Height    Weight
0       1  0.744399  0.862415
1       1  0.548328  0.472703
2       1  0.754583  0.719657
3       1  0.662487  0.755412
4       1  0.590905  0.688360

In [14]:
x = df.drop('Gender', axis = 1,)

In [15]:
y = df['Gender']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.30,random_state=101)

# KNN Classifier

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knn = KNeighborsClassifier()

In [20]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [25]:
y_pred = knn.predict(x_test)

In [37]:
from sklearn.metrics import classification_report, confusion_matrix, roc_curve

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.88      0.87      1071
           1       0.91      0.89      0.90      1496

    accuracy                           0.89      2567
   macro avg       0.88      0.88      0.88      2567
weighted avg       0.89      0.89      0.89      2567



In [34]:
print(confusion_matrix(y_test, y_pred))

[[ 942  129]
 [ 165 1331]]


In [38]:
print(roc_curve(y_test,y_pred))

(array([0.        , 0.12044818, 1.        ]), array([0.        , 0.88970588, 1.        ]), array([2, 1, 0]))


# DecisionTree Classifier

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
dtc = DecisionTreeClassifier()

In [23]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [26]:
y_pred = dtc.predict(x_test)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, plot_roc_curve

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.88      0.87      1071
           1       0.91      0.89      0.90      1496

    accuracy                           0.89      2567
   macro avg       0.88      0.88      0.88      2567
weighted avg       0.89      0.89      0.89      2567



In [31]:
print(confusion_matrix(y_test, y_pred))

[[ 942  129]
 [ 165 1331]]


In [36]:
print(roc_curve(y_test,y_pred))

(array([0.        , 0.12044818, 1.        ]), array([0.        , 0.88970588, 1.        ]), array([2, 1, 0]))


# RandomForest Classifier

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
rfc = RandomForestClassifier(n_estimators = 100)

In [42]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [43]:
rfc_pred = rfc.predict(x_test)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, plot_roc_curve

In [45]:
print(confusion_matrix(y_test, rfc_pred))

[[ 965  106]
 [ 139 1357]]


In [46]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.87      0.90      0.89      1071
           1       0.93      0.91      0.92      1496

    accuracy                           0.90      2567
   macro avg       0.90      0.90      0.90      2567
weighted avg       0.91      0.90      0.90      2567

