In [109]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from datetime import timedelta
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [14]:
df = pd.read_csv('Submission_GMM_RFC.csv')

In [15]:
df.head()

Id  Solution
0   1         1
1   2         0
2   3         1
3   4         0
4   5         0

In [16]:
df.value_counts()

Id    Solution
1     1           1
6003  0           1
5997  1           1
5998  1           1
5999  1           1
                 ..
2995  1           1
2994  0           1
2993  0           1
2992  1           1
9000  1           1
Length: 9000, dtype: int64

In [17]:
df.drop_duplicates(inplace = True)

In [18]:
df.isnull().sum()

Id          0
Solution    0
dtype: int64

In [19]:
df.shape

(9000, 2)

In [20]:
df.describe()

Id     Solution
count  9000.000000  9000.000000
mean   4500.500000     0.500222
std    2598.220545     0.500028
min       1.000000     0.000000
25%    2250.750000     0.000000
50%    4500.500000     1.000000
75%    6750.250000     1.000000
max    9000.000000     1.000000

In [23]:
x = df[['Id']]

In [25]:
y = df['Solution']

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=.30, random_state=101)

# Naive_Bayes

In [29]:
from sklearn.naive_bayes import GaussianNB

In [30]:
gnb = GaussianNB()

In [31]:
gnb.fit(x_train,y_train)

GaussianNB()

In [83]:
gnb_pred = gnb.predict(x_test)

In [84]:
gnb_pred

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [110]:
print(classification_report(y_test,gnb_pred))

              precision    recall  f1-score   support

           0       0.50      0.42      0.46      1357
           1       0.50      0.57      0.53      1343

    accuracy                           0.50      2700
   macro avg       0.50      0.50      0.50      2700
weighted avg       0.50      0.50      0.49      2700



In [85]:
print(confusion_matrix(y_test,gnb_pred))

[[573 784]
 [572 771]]


In [87]:
print(accuracy_score(y_test,gnb_pred))

0.49777777777777776


In [116]:
gnb.score(x_test,y_test)

0.49777777777777776

In [132]:
from sklearn.naive_bayes import BernoulliNB

In [133]:
bn = BernoulliNB()

In [134]:
bn.fit(x_train,y_train)

BernoulliNB()

In [136]:
bn_pred = bn.predict(x_test)

In [137]:
bn_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [138]:
bn.score(x_test,y_test)

0.4974074074074074

In [139]:
print(confusion_matrix(y_test,bn_pred))

[[   0 1357]
 [   0 1343]]


In [140]:
print(classification_report(y_test,bn_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1357
           1       0.50      1.00      0.66      1343

    accuracy                           0.50      2700
   macro avg       0.25      0.50      0.33      2700
weighted avg       0.25      0.50      0.33      2700



In [141]:
print(accuracy_score(y_test,bn_pred))

0.4974074074074074


In [142]:
from sklearn.naive_bayes import MultinomialNB

In [145]:
mnb = MultinomialNB()

In [147]:
mnb.fit(x_train,y_train)

MultinomialNB()

In [148]:
mnb_pred =mnb.predict(x_test)

In [149]:
mnb_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [150]:
print(confusion_matrix(y_test,mnb_pred))

[[   0 1357]
 [   0 1343]]


In [151]:
print(classification_report(y_test,mnb_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1357
           1       0.50      1.00      0.66      1343

    accuracy                           0.50      2700
   macro avg       0.25      0.50      0.33      2700
weighted avg       0.25      0.50      0.33      2700



In [152]:
print(accuracy_score(y_test,mnb_pred))

0.4974074074074074


# KNN Classifier

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
knn = KNeighborsClassifier()

In [36]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [88]:
knn_pred = knn.predict(x_test)

In [89]:
knn_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [111]:
print(classification_report(y_test,knn_pred))

              precision    recall  f1-score   support

           0       0.51      0.51      0.51      1357
           1       0.51      0.50      0.51      1343

    accuracy                           0.51      2700
   macro avg       0.51      0.51      0.51      2700
weighted avg       0.51      0.51      0.51      2700



In [90]:
print(confusion_matrix(y_test,knn_pred))

[[698 659]
 [665 678]]


In [91]:
print(accuracy_score(y_test,knn_pred))

0.5096296296296297


In [117]:
knn.score(x_test,y_test)

0.5096296296296297

# RandomForest

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
rfc = RandomForestClassifier()

In [42]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [93]:
rfc_pred = rfc.predict(x_test)

In [94]:
rfc_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [112]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.51      0.52      0.51      1357
           1       0.50      0.49      0.50      1343

    accuracy                           0.51      2700
   macro avg       0.51      0.51      0.51      2700
weighted avg       0.51      0.51      0.51      2700



In [95]:
print(confusion_matrix(y_test,rfc_pred))

[[706 651]
 [683 660]]


In [96]:
print(accuracy_score(y_test,rfc_pred))

0.5059259259259259


In [118]:
rfc.score(x_test,y_test)

0.5059259259259259

# LogisticRegression

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
lr = LogisticRegression()

In [49]:
lr.fit(x_train,y_train)

LogisticRegression()

In [97]:
lr_pred = lr.predict(x_test)

In [98]:
lr_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [113]:
print(classification_report(y_test,lr_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1357
           1       0.50      1.00      0.66      1343

    accuracy                           0.50      2700
   macro avg       0.25      0.50      0.33      2700
weighted avg       0.25      0.50      0.33      2700



In [99]:
print(confusion_matrix(y_test,lr_pred))

[[   0 1357]
 [   0 1343]]


In [100]:
print(accuracy_score(y_test,lr_pred))

0.4974074074074074


In [119]:
lr.score(x_test,y_test)

0.4974074074074074

# SVM

In [121]:
from sklearn.svm import SVC

In [122]:
svc = SVC()

In [123]:
svc.fit(x_train,y_train)

SVC()

In [124]:
svm_pred = svc.predict(x_test)

In [125]:
svm_pred

array([0, 1, 0, ..., 0, 1, 1], dtype=int64)

In [114]:
print(classification_report(y_test,svm_pred))

              precision    recall  f1-score   support

           0       0.51      0.38      0.43      1357
           1       0.50      0.63      0.56      1343

    accuracy                           0.50      2700
   macro avg       0.50      0.50      0.49      2700
weighted avg       0.50      0.50      0.49      2700



In [127]:
print(confusion_matrix(y_test,svm_pred))

[[511 846]
 [500 843]]


In [128]:
print(accuracy_score(y_test,svm_pred))

0.5014814814814815


In [130]:
svc.score(x_test,y_test)

0.5014814814814815

# DecisionTreeClassifier

In [58]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
dtc = DecisionTreeClassifier()

In [60]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [105]:
dtc_pred = dtc.predict(x_test)

In [106]:
dtc_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [115]:
print(classification_report(y_test,dtc_pred))

              precision    recall  f1-score   support

           0       0.51      0.52      0.51      1357
           1       0.50      0.49      0.50      1343

    accuracy                           0.51      2700
   macro avg       0.51      0.51      0.51      2700
weighted avg       0.51      0.51      0.51      2700



In [107]:
print(confusion_matrix(y_test,dtc_pred))

[[705 652]
 [683 660]]


In [108]:
print(accuracy_score(y_test,dtc_pred))

0.5055555555555555


In [131]:
dtc.score(x_test,y_test)

0.5055555555555555