In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from datetime import timedelta
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Submission_GMM_RFC.csv')

In [3]:
df.head()

Id  Solution
0   1         1
1   2         0
2   3         1
3   4         0
4   5         0

In [4]:
df.value_counts()

Id    Solution
1     1           1
6003  0           1
5997  1           1
5998  1           1
5999  1           1
                 ..
2995  1           1
2994  0           1
2993  0           1
2992  1           1
9000  1           1
Length: 9000, dtype: int64

In [5]:
df.drop_duplicates(inplace = True)

In [6]:
df.isnull().sum()

Id          0
Solution    0
dtype: int64

In [101]:
df.isna().sum()

Id          0
Solution    0
dtype: int64

In [7]:
df.shape

(9000, 2)

In [8]:
df.describe()

Id     Solution
count  9000.000000  9000.000000
mean   4500.500000     0.500222
std    2598.220545     0.500028
min       1.000000     0.000000
25%    2250.750000     0.000000
50%    4500.500000     1.000000
75%    6750.250000     1.000000
max    9000.000000     1.000000

In [9]:
x = df[['Id']]

In [10]:
y = df['Solution']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=.30, random_state=101)

# 1. Naive_Bayes

In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
gnb = GaussianNB()

In [15]:
gnb.fit(x_train,y_train)

GaussianNB()

In [16]:
gnb_pred = gnb.predict(x_test)

In [17]:
gnb_pred

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [18]:
print(classification_report(y_test,gnb_pred))

              precision    recall  f1-score   support

           0       0.50      0.42      0.46      1357
           1       0.50      0.57      0.53      1343

    accuracy                           0.50      2700
   macro avg       0.50      0.50      0.50      2700
weighted avg       0.50      0.50      0.49      2700



In [19]:
print(confusion_matrix(y_test,gnb_pred))

[[573 784]
 [572 771]]


In [20]:
print(accuracy_score(y_test,gnb_pred))

0.49777777777777776


In [21]:
gnb.score(x_test,y_test)

0.49777777777777776

In [22]:
from sklearn.naive_bayes import BernoulliNB

In [23]:
bn = BernoulliNB()

In [24]:
bn.fit(x_train,y_train)

BernoulliNB()

In [25]:
bn_pred = bn.predict(x_test)

In [26]:
bn_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [27]:
bn.score(x_test,y_test)

0.4974074074074074

In [28]:
print(confusion_matrix(y_test,bn_pred))

[[   0 1357]
 [   0 1343]]


In [29]:
print(classification_report(y_test,bn_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1357
           1       0.50      1.00      0.66      1343

    accuracy                           0.50      2700
   macro avg       0.25      0.50      0.33      2700
weighted avg       0.25      0.50      0.33      2700



In [30]:
print(accuracy_score(y_test,bn_pred))

0.4974074074074074


In [31]:
from sklearn.naive_bayes import MultinomialNB

In [32]:
mnb = MultinomialNB()

In [33]:
mnb.fit(x_train,y_train)

MultinomialNB()

In [34]:
mnb_pred =mnb.predict(x_test)

In [35]:
mnb_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [36]:
print(confusion_matrix(y_test,mnb_pred))

[[   0 1357]
 [   0 1343]]


In [37]:
print(classification_report(y_test,mnb_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1357
           1       0.50      1.00      0.66      1343

    accuracy                           0.50      2700
   macro avg       0.25      0.50      0.33      2700
weighted avg       0.25      0.50      0.33      2700



In [38]:
print(accuracy_score(y_test,mnb_pred))

0.4974074074074074


# 2. KNN Classifier

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
knn = KNeighborsClassifier()

In [41]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [42]:
knn_pred = knn.predict(x_test)

In [43]:
knn_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [44]:
print(classification_report(y_test,knn_pred))

              precision    recall  f1-score   support

           0       0.51      0.51      0.51      1357
           1       0.51      0.50      0.51      1343

    accuracy                           0.51      2700
   macro avg       0.51      0.51      0.51      2700
weighted avg       0.51      0.51      0.51      2700



In [45]:
print(confusion_matrix(y_test,knn_pred))

[[698 659]
 [665 678]]


In [46]:
print(accuracy_score(y_test,knn_pred))

0.5096296296296297


In [47]:
knn.score(x_test,y_test)

0.5096296296296297

# 3. RandomForest

In [48]:
from sklearn.ensemble import RandomForestClassifier

In [49]:
rfc = RandomForestClassifier()

In [50]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [51]:
rfc_pred = rfc.predict(x_test)

In [52]:
rfc_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.51      0.52      0.51      1357
           1       0.50      0.49      0.50      1343

    accuracy                           0.50      2700
   macro avg       0.50      0.50      0.50      2700
weighted avg       0.50      0.50      0.50      2700



In [54]:
print(confusion_matrix(y_test,rfc_pred))

[[705 652]
 [685 658]]


In [55]:
print(accuracy_score(y_test,rfc_pred))

0.5048148148148148


In [56]:
rfc.score(x_test,y_test)

0.5048148148148148

# 4. LogisticRegression

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
lr = LogisticRegression()

In [59]:
lr.fit(x_train,y_train)

LogisticRegression()

In [60]:
lr_pred = lr.predict(x_test)

In [61]:
lr_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [62]:
print(classification_report(y_test,lr_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1357
           1       0.50      1.00      0.66      1343

    accuracy                           0.50      2700
   macro avg       0.25      0.50      0.33      2700
weighted avg       0.25      0.50      0.33      2700



In [63]:
print(confusion_matrix(y_test,lr_pred))

[[   0 1357]
 [   0 1343]]


In [64]:
print(accuracy_score(y_test,lr_pred))

0.4974074074074074


In [65]:
lr.score(x_test,y_test)

0.4974074074074074

# 5. SVM

In [66]:
from sklearn.svm import SVC

In [67]:
svc = SVC()

In [68]:
svc.fit(x_train,y_train)

SVC()

In [69]:
svm_pred = svc.predict(x_test)

In [70]:
svm_pred

array([0, 1, 0, ..., 0, 1, 1], dtype=int64)

In [71]:
print(classification_report(y_test,svm_pred))

              precision    recall  f1-score   support

           0       0.51      0.38      0.43      1357
           1       0.50      0.63      0.56      1343

    accuracy                           0.50      2700
   macro avg       0.50      0.50      0.49      2700
weighted avg       0.50      0.50      0.49      2700



In [72]:
print(confusion_matrix(y_test,svm_pred))

[[511 846]
 [500 843]]


In [73]:
print(accuracy_score(y_test,svm_pred))

0.5014814814814815


In [74]:
svc.score(x_test,y_test)

0.5014814814814815

# 6. DecisionTreeClassifier

In [75]:
from sklearn.tree import DecisionTreeClassifier

In [76]:
dtc = DecisionTreeClassifier()

In [77]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [78]:
dtc_pred = dtc.predict(x_test)

In [79]:
dtc_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [80]:
print(classification_report(y_test,dtc_pred))

              precision    recall  f1-score   support

           0       0.51      0.52      0.51      1357
           1       0.50      0.49      0.50      1343

    accuracy                           0.51      2700
   macro avg       0.51      0.51      0.51      2700
weighted avg       0.51      0.51      0.51      2700



In [81]:
print(confusion_matrix(y_test,dtc_pred))

[[705 652]
 [683 660]]


In [82]:
print(accuracy_score(y_test,dtc_pred))

0.5055555555555555


In [83]:
dtc.score(x_test,y_test)

0.5055555555555555

# 7.GradientBoosting

In [86]:
from sklearn.ensemble import GradientBoostingClassifier

In [87]:
gb = GradientBoostingClassifier()

In [88]:
gb.fit(x_train,y_train)

GradientBoostingClassifier()

In [89]:
gb_pred = gb.predict(x_test)

In [90]:
gb_pred

array([0, 1, 0, ..., 0, 1, 1], dtype=int64)

In [91]:
print(confusion_matrix(y_test,gb_pred))

[[753 604]
 [731 612]]


In [92]:
print(accuracy_score(y_test,gb_pred))

0.5055555555555555


# 8.AdaBoost

In [93]:
from sklearn.ensemble import AdaBoostClassifier

In [94]:
ab = AdaBoostClassifier()

In [95]:
ab.fit(x_train,y_train)

AdaBoostClassifier()

In [96]:
ab_pred = ab.predict(x_test)

In [97]:
ab_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [98]:
print(confusion_matrix(y_test,ab_pred))

[[875 482]
 [864 479]]


In [99]:
print(accuracy_score(y_test,ab_pred))

0.5014814814814815
