In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Loan_Data.csv')

In [3]:
df.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   credit.policy      9578 non-null   int64  
 1   purpose            9578 non-null   object 
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64  
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64  
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64  
 11  delinq.2yrs        9578 non-null   int64  
 12  pub.rec            9578 non-null   int64  
 13  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [5]:
df.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [6]:
purpose1 = pd.get_dummies(df['purpose'],drop_first=True)

In [7]:
purpose1

credit_card  debt_consolidation  educational  home_improvement  \
0               0                   1            0                 0   
1               1                   0            0                 0   
2               0                   1            0                 0   
3               0                   1            0                 0   
4               1                   0            0                 0   
...           ...                 ...          ...               ...   
9573            0                   0            0                 0   
9574            0                   0            0                 0   
9575            0                   1            0                 0   
9576            0                   0            0                 1   
9577            0                   1            0                 0   

      major_purchase  small_business  
0                  0               0  
1                  0               0  
2                  0               0  
3                  0               0  
4                  0               0  
...              ...             ...  
9573               0               0  
9574               0               0  
9575               0               0  
9576               0               0  
9577               0               0  

[9578 rows x 6 columns]

In [8]:
df = df.drop(['purpose'],axis=1)

In [9]:
df = pd.concat([df,purpose1],axis=1)

In [10]:
df

credit.policy  int.rate  installment  log.annual.inc    dti  fico  \
0                 1    0.1189       829.10       11.350407  19.48   737   
1                 1    0.1071       228.22       11.082143  14.29   707   
2                 1    0.1357       366.86       10.373491  11.63   682   
3                 1    0.1008       162.34       11.350407   8.10   712   
4                 1    0.1426       102.92       11.299732  14.97   667   
...             ...       ...          ...             ...    ...   ...   
9573              0    0.1461       344.76       12.180755  10.39   672   
9574              0    0.1253       257.70       11.141862   0.21   722   
9575              0    0.1071        97.81       10.596635  13.09   687   
9576              0    0.1600       351.58       10.819778  19.18   692   
9577              0    0.1392       853.43       11.264464  16.28   732   

      days.with.cr.line  revol.bal  revol.util  inq.last.6mths  delinq.2yrs  \
0           5639.958333      28854        52.1               0            0   
1           2760.000000      33623        76.7               0            0   
2           4710.000000       3511        25.6               1            0   
3           2699.958333      33667        73.2               1            0   
4           4066.000000       4740        39.5               0            1   
...                 ...        ...         ...             ...          ...   
9573       10474.000000     215372        82.1               2            0   
9574        4380.000000        184         1.1               5            0   
9575        3450.041667      10036        82.9               8            0   
9576        1800.000000          0         3.2               5            0   
9577        4740.000000      37879        57.0               6            0   

      pub.rec  not.fully.paid  credit_card  debt_consolidation  educational  \
0           0               0            0                   1            0   
1           0               0            1                   0            0   
2           0               0            0                   1            0   
3           0               0            0                   1            0   
4           0               0            1                   0            0   
...       ...             ...          ...                 ...          ...   
9573        0               1            0                   0            0   
9574        0               1            0                   0            0   
9575        0               1            0                   1            0   
9576        0               1            0                   0            0   
9577        0               1            0                   1            0   

      home_improvement  major_purchase  small_business  
0                    0               0               0  
1                    0               0               0  
2                    0               0               0  
3                    0               0               0  
4                    0               0               0  
...                ...             ...             ...  
9573                 0               0               0  
9574                 0               0               0  
9575                 0               0               0  
9576                 1               0               0  
9577                 0               0               0  

[9578 rows x 19 columns]

In [11]:
x = df.drop(['not.fully.paid'],axis=1)

In [12]:
y= df['not.fully.paid']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.30,random_state=101)

# DecisionTreeClassifier

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
dt=DecisionTreeClassifier()

In [17]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [18]:
dt_pred = dt.predict(xtest)

In [19]:
dt_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix


In [21]:
print(classification_report(ytest,dt_pred))

              precision    recall  f1-score   support

           0       0.85      0.82      0.84      2431
           1       0.19      0.23      0.20       443

    accuracy                           0.73      2874
   macro avg       0.52      0.52      0.52      2874
weighted avg       0.75      0.73      0.74      2874



In [22]:
print(confusion_matrix(ytest,dt_pred))

[[1996  435]
 [ 343  100]]


In [23]:
print(accuracy_score(ytest,dt_pred))

0.7292971468336813


# RandomForestClassifier

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf = RandomForestClassifier(n_estimators = 300)

In [26]:
rf.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=300)

In [27]:
rf_pred = rf.predict(xtest)

In [28]:
rf_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
print(confusion_matrix(ytest,rf_pred))

[[2422    9]
 [ 435    8]]


In [30]:
print(classification_report(ytest,rf_pred))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2431
           1       0.47      0.02      0.03       443

    accuracy                           0.85      2874
   macro avg       0.66      0.51      0.48      2874
weighted avg       0.79      0.85      0.78      2874



In [31]:
print(accuracy_score(ytest,rf_pred))

0.8455114822546973


# LogisticRegression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
lr = LogisticRegression()

In [34]:
lr.fit(xtrain,ytrain)

LogisticRegression()

In [37]:
lr_pred = lr.predict(xtest)

In [38]:
lr_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
print(confusion_matrix(ytest,lr_pred))

[[2425    6]
 [ 433   10]]


In [40]:
print(classification_report(ytest,lr_pred))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      2431
           1       0.62      0.02      0.04       443

    accuracy                           0.85      2874
   macro avg       0.74      0.51      0.48      2874
weighted avg       0.81      0.85      0.78      2874



In [41]:
print(accuracy_score(ytest,lr_pred))

0.8472512178148921
