In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [53]:
df = pd.read_csv('music.csv')

In [54]:
df.head()

age  gender   genre
0   20       1  HipHop
1   23       1  HipHop
2   25       1  HipHop
3   26       1    Jazz
4   29       1    Jazz

In [17]:
df.shape

(18, 3)

In [18]:
df.describe()

age     gender
count  18.000000  18.000000
mean   27.944444   0.500000
std     5.127460   0.514496
min    20.000000   0.000000
25%    25.000000   0.000000
50%    28.000000   0.500000
75%    31.000000   1.000000
max    37.000000   1.000000

In [19]:
df.isnull().sum()

age       0
gender    0
genre     0
dtype: int64

In [40]:
x = df.iloc[:,:2]

In [41]:
x

age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [55]:
y = df['genre']

In [56]:
y

0        HipHop
1        HipHop
2        HipHop
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10        Dance
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
Name: genre, dtype: object

In [57]:
from sklearn.model_selection import train_test_split

In [79]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.20,random_state=1)

In [76]:
from sklearn.tree import DecisionTreeClassifier

In [77]:
dt = DecisionTreeClassifier()

In [81]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [97]:
y_pred = dt.predict(x_test)

In [98]:
y_pred

array(['Classical', 'HipHop', 'Acoustic', 'HipHop'], dtype=object)

In [84]:
#y_pred = dt.predict([[21,1]])

In [85]:
#y_pred

array(['HipHop'], dtype=object)

In [99]:
dt.score(x_test,y_test)

0.75

In [100]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [101]:
print(confusion_matrix(y_test,y_pred))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 0]]


In [102]:
print(accuracy_score(y_test,y_pred))

0.75


In [103]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

    Acoustic       1.00      1.00      1.00         1
   Classical       1.00      1.00      1.00         1
      HipHop       0.50      1.00      0.67         1
        Jazz       0.00      0.00      0.00         1

    accuracy                           0.75         4
   macro avg       0.62      0.75      0.67         4
weighted avg       0.62      0.75      0.67         4

