In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [47]:
df = pd.read_csv('emails.csv')

In [48]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
df.shape

(5728, 2)

In [5]:
df.value_counts('spam')

spam
0    4360
1    1368
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(5695, 2)

In [8]:
df['text']

0       Subject: naturally irresistible your corporate...
1       Subject: the stock trading gunslinger  fanny i...
2       Subject: unbelievable new homes made easy  im ...
3       Subject: 4 color printing special  request add...
4       Subject: do not have money , get software cds ...
                              ...                        
5723    Subject: re : research and development charges...
5724    Subject: re : receipts from visit  jim ,  than...
5725    Subject: re : enron case study update  wow ! a...
5726    Subject: re : interest  david ,  please , call...
5727    Subject: news : aurora 5 . 2 update  aurora ve...
Name: text, Length: 5695, dtype: object

In [9]:
df['text'][0]

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  ma

In [10]:
df['text'][3]

'Subject: 4 color printing special  request additional information now ! click here  click here for a printable version of our order form ( pdf format )  phone : ( 626 ) 338 - 8090 fax : ( 626 ) 338 - 8102 e - mail : ramsey @ goldengraphix . com  request additional information now ! click here  click here for a printable version of our order form ( pdf format )  golden graphix & printing 5110 azusa canyon rd . irwindale , ca 91706 this e - mail message is an advertisement and / or solicitation . '

In [11]:
import nltk
import string
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sohel\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
from nltk.corpus import stopwords, words

In [13]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [14]:
li = [1,2,3,4,5,6]
[i for i in li]

[1, 2, 3, 4, 5, 6]

In [15]:
[i for i in li if (i%2)!=0]

[1, 3, 5]

In [16]:
'data science'.split()

['data', 'science']

In [17]:
ch = 'data science!!!'
ch2 = [char for char in ch if char not in string.punctuation] #example

In [18]:
ch2

['d', 'a', 't', 'a', ' ', 's', 'c', 'i', 'e', 'n', 'c', 'e']

In [19]:
''.join(ch2)

'data science'

# Text Processing

In [20]:
def clean_text_data(text):
    remove_punc1 = [char for char in text if char not in string.punctuation] #Without punctuation all character 
    remove_punc2 = ''.join(remove_punc1) #sentence without punction
    
    stop_words_remove = [word for word in remove_punc2.split() if word.lower() in stopwords.words('english')]
    return stop_words_remove

In [21]:
df['text'].head()# old text

0    Subject: naturally irresistible your corporate...
1    Subject: the stock trading gunslinger  fanny i...
2    Subject: unbelievable new homes made easy  im ...
3    Subject: 4 color printing special  request add...
4    Subject: do not have money , get software cds ...
Name: text, dtype: object

In [22]:
df['text'].head().apply(clean_text_data) #new text

0    [your, is, to, a, the, is, of, and, the, but, ...
1    [the, is, but, not, and, is, not, or, no, is, ...
2    [to, you, this, you, have, been, for, a, at, a...
3    [now, here, here, for, a, of, our, now, here, ...
4    [do, not, have, from, here, ain, t, it, with, ...
Name: text, dtype: object

In [23]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer


In [24]:
tf = TfidfVectorizer(analyzer = clean_text_data).fit_transform(df['text'])

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(tf,df['spam'], test_size=.30, random_state=101)

In [27]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

In [28]:
x_train.shape

(3986, 151)

# MultinomialNB

In [29]:
multi = MultinomialNB()

In [30]:
multi.fit(x_train,y_train)

MultinomialNB()

In [31]:
multi.predict(x_test)

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
multi.score(x_test,y_test)

0.8291398478642481

# BernoulliNB

In [33]:
ber = BernoulliNB() 

In [34]:
ber.fit(x_train,y_train)

BernoulliNB()

In [35]:
ber.predict(x_test)

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [51]:
ber.score(x_test,y_test)

0.770040959625512

# GaussianNB

In [37]:
tf

<5695x151 sparse matrix of type '<class 'numpy.float64'>'
	with 173475 stored elements in Compressed Sparse Row format>

In [45]:
print(tf.toarray())

[[0.2473737  0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.28481079 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.11302677 0.         0.         ... 0.         0.         0.        ]
 [0.13675414 0.12794634 0.         ... 0.         0.         0.        ]
 [0.11767047 0.05504589 0.         ... 0.         0.         0.        ]]


In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(tf.toarray(),df['spam'], test_size=.30, random_state=101)

In [41]:
gu =  GaussianNB()

In [42]:
gu.fit(x_train,y_train)

GaussianNB()

In [43]:
gu.predict(x_test)

array([0, 1, 0, ..., 1, 0, 1], dtype=int64)

In [50]:
gu.score(x_test,y_test)

0.6957284961966061