In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from datetime import timedelta
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('mail_data.csv')

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
df.shape

(5572, 2)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()

In [8]:
df.Category = le.fit_transform(df['Category'])

In [9]:
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [10]:
y = df.Category.values

In [11]:
x = df.Message.values

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=.30, random_state=101)

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tv = TfidfVectorizer()

In [16]:
xtrain = tv.fit_transform(x_train) 

In [23]:
xtrain.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
xtest = tv.fit_transform(x_test)

In [24]:
xtest.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
lr = LogisticRegression()

In [20]:
lr.fit(xtrain,y_train)

LogisticRegression()

In [27]:
y_pred = lr.predict(xtrain) #####

In [28]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99      3350
           1       1.00      0.82      0.90       550

    accuracy                           0.97      3900
   macro avg       0.98      0.91      0.94      3900
weighted avg       0.97      0.97      0.97      3900



In [33]:
print(confusion_matrix(y_train,y_pred))

[[3348    2]
 [  99  451]]


In [31]:
print(accuracy_score(y_train,y_pred))

0.9741025641025641


In [34]:
from sklearn.naive_bayes import MultinomialNB

In [35]:
mnb = MultinomialNB()

In [36]:
mnb.fit(xtrain,y_train)

MultinomialNB()

In [38]:
y_prediction = mnb.predict(xtrain) #####

In [39]:
y_prediction

array([0, 0, 0, ..., 0, 0, 0])

In [40]:
print(accuracy_score(y_train,y_prediction))

0.9733333333333334
